# Lab 4, Part 3 – NumPy
## CSS Summer Bootcamp, Week 1 🥾

In [ ]:
# Run this cell, and don't change it!
!pip install otter-grader

In [ ]:
# Run this cell, and don't change it!
import otter
grader = otter.Notebook()

from ipywidgets import widgets
from PIL import Image
import io
import pandas as pd

## Question 1 – NumPy Fundamentals

In this question, we'll take a closer look at a few functions in NumPy.

In [ ]:
import numpy as np

Before working on this section you may want to make sure you understand the following key examples:

In [ ]:
x = np.array([5, 9, 1, 0, -8, 6])
y = np.arange(6)

In [ ]:
2 * x - 5

In [ ]:
x + y

### Question 1a

It is often said that "one dog year is equal to seven human years." [This isn't entirely accurate](https://www.akc.org/expert-advice/health/how-to-calculate-dog-years-to-human-years/), but we will assume it is true for this question.

Below, implement the function `dog_to_human`, which takes in an array of ages in dog years and outputs an array of human years (these are arrays – not lists!). Example behavior is shown below.

```py
>>> dog_to_human(np.array([3, 8, 11, 4, 9]))
array([21, 56, 77, 28, 63])

>>> dog_to_human(np.arange(10))
array([0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 72, 81])
```


**Here's the catch: you cannot use a for loop, and your function can only have one line.** This is not a trick question; it should be very straightforward given what we covered in lecture.

***Hint:*** review how arithmetic operations work with arrays.

<!--
BEGIN QUESTION
name: q1a
points: 1
-->

In [ ]:
def dog_to_human(ages):
    ...

In [ ]:
grader.check("q1a")

### Question 1b

Suppose you're a waiter, and you've kept track of all of the bills you've given to tables along with the tips they gave you over a period of time in two separate arrays, `bills` and `tips`. One number of interest to you is the tip percentage each table gave you. Tip percentages are calculated according to the formula

$$\text{Tip Percentage} = 100 \cdot \frac{\text{Tip}}{\text{Bill}}$$

Below, implement the function `tip_percentage`, which takes in two arrays `bills` and `tips` and returns an array of tip percentages. Example behavior is shown below.

```py
>>> tip_percentage(np.array([25, 50, 75]), np.array([15, 15, 15]))
array([60., 30., 20.])
# Note: 60. is the same as 60.0; numpy is just weird

>>> tip_percentage(np.array([50, 70, 100, 95, 25]), np.array([10, 10, 25, 35, 7]))
array([20., 14.28571429, 25., 36.84210526, 28.])
```

**Again, you cannot use a for loop, and your function can only have one line.**

<!--
BEGIN QUESTION
name: q1b
points: 1
-->

In [ ]:
def tip_percentage(bills, tips):
    ...

In [ ]:
grader.check("q1b")

### Question 1c

The [Basel problem](https://en.wikipedia.org/wiki/Basel_problem) was a mathematical challenge first issued in 1650. The challenge was to determine the value of the following infinite sum, which we'll call the "Basel sum":

$$\sum_{k = 1}^n \frac{1}{k^2} = \frac{1}{1^2} + \frac{1}{2^2} + \frac{1}{3^2} + \frac{1}{4^2} + \frac{1}{5^2} + ... + \frac{1}{10000^2} + ...$$

Leonard Euler (the same person who $e$ is named after) determined the value of the Basel sum is exactly $\frac{\pi^2}{6}$.

In this subpart, we'll try and prove to ourselves that Euler is right, without using any fancy math. Instead, we'll use what we know about for loops and arrays – and along the way, we'll show you how much faster `numpy` arrays are at certain tasks than for loops.

First, we should acknowledge that while the above sum is infinite, computers don't understand the idea of infinity. So we'll have to settle for summing a lot terms of the above summation and checking to see if the result is close to $\frac{\pi^2}{6}$. We'll sum ten million (`10**7`) terms.

#### For Loop

First, we'll sum ten million terms of the Basel sum using a for loop, and store our answer in `basel_sum_for`. This has already been done for you, just run the following cell.

In [ ]:
%%time

basel_sum_for = 0
for i in range(1, 10**7 + 1):
    basel_sum_for += 1 / (i**2)
    
print('result using for loop: ', basel_sum_for, '\n\n')

The number next to `total:` above tells us the amount of time it took to run the above cell.

The resulting value does look pretty close to $\frac{\pi^2}{6}$:

In [ ]:
# np.pi is a variable built into numpy

(np.pi ** 2) / 6

#### Arrays

Now, instead of using a for loop, it's your turn to compute the Basel sum using an array.

Below, assign `basel_array` to an array with ten million elements, each of which is one term of the Basel sum sequence. `basel_array[0]` should be $\frac{1}{1^2}$, `basel_array[1]` should be $\frac{1}{2^2}$, and so on.

After you assign `basel_array` correctly, assign `basel_sum_arr` to the sum of your ten million-element array `basel_arr`, using `np.sum`. The result you get should be very close to `basel_sum_for`.

**To compute `basel_arr`, start by calling `np.arange` with the arguments that were used with `range` in the for loop above. Both `basel_arr` and `basel_arr_sum` should be computed in one line each!**

<!--
BEGIN QUESTION
name: q1c
points: 2
-->

In [ ]:
%%time

basel_arr = ...
    
basel_sum_arr = ...
print('result using numpy arrays: ', basel_sum_arr, '\n\n')

In [ ]:
grader.check("q1c")

If you did things correctly, you should see that `basel_sum_arr` is pretty close to `basel_sum_for`. However, the time it took for `basel_sum_arr` to be computed is roughly a quarter of the time it took for `basel_sum_for` to be computed! Hopefully, this drives home the point that NumPy arrays are quite powerful.

### Question 1d

Below, we load in the year-wise global population dataset we looked at in Lab 2A, but this time as an array.

In [ ]:
population = pd.read_csv('data/world_population_2022.csv')['Population'].to_numpy()
population

The first year in the dataset is 1950.

In [ ]:
# Population in 1950
population[0]

The last year in the dataset is 2022.

In [ ]:
population[72]

In [ ]:
len(population)

Answer the following subproblems involving `population`.

#### Part 1

Assign `num_above_5_bill` to the **number of years** that the world's population has been above 5,000,000.

***Hint:*** Use Boolean indexing. Don't count manually, and don't use a `for`-loop!

<!--
BEGIN QUESTION
name: q1d-part1
-->

In [ ]:
num_above_5_bill = np.sum(population >= 5 * (10 ** 9))
num_above_5_bill

In [ ]:
grader.check("q1d-part1")

#### Part 2

Assign `changes` to an array containing the **differences** in yearly populations. `changes` should have 1 fewer element than `population`. For example, the first element in `changes` should be `37322630`, since that's the difference between the population in 1951 and the population in 1950.

***Hint:*** This only involves a single line of code. If you're not sure how to proceed, take a look at the slide titled "Even more functions..." in the most recent lecture.

<!--
BEGIN QUESTION
name: q1d-part2
-->

In [ ]:
changes = ...
changes

In [ ]:
grader.check("q1d-part2")

#### Part 3

The function `np.argmax` returns the position (index) of the largest element in an array.

In [ ]:
np.argmax(np.array([5, 2, 1, 9, 3]))

Using `np.argmax` (and perhaps other arithmetic), determine the year that saw the largest population increase over the previous year, in terms of raw number of people. For instance, if the answer is 1982, what that would mean is that the difference between the population in 1982 and 1981 is larger than the difference between the populations in any other two consecutive years in the dataset. Assign your result to `biggest_change`.

<!--
BEGIN QUESTION
name: q1d-part3
-->

In [ ]:
biggest_change = ...
biggest_change

In [ ]:
grader.check("q1d-part3")

#### Part 4

Recall, to compute the percentage increase between an initial value and a final value, we use the formula:

$$\text{% change} = 100\% \cdot \frac{\text{Final} - \text{Initial}}{\text{Initial}}$$

What year saw the largest population increase over the previous year, **as a percentage**? Assign your result to `biggest_change_pct`.

***Hint:*** This is tricky. Our answer still only uses one line, and uses both `changes` and `population`.


<!--
BEGIN QUESTION
name: q1d-part4
-->

In [ ]:
biggest_change_pct = ...
biggest_change_pct

In [ ]:
grader.check("q1d-part4")

## Question 2 – #nofilter

In this question, you will write code that applies greyscale, sepia, and x-ray filters to images! Run the cell below to get started.

In [ ]:
# Don't worry about what this code is doing, just run it.
import skimage.io as skio
import matplotlib.pyplot as plt

def show_image(image_array):
    plt.figure(figsize = (10, 5))
    plt.imshow(image_array)
    plt.axis('off');
    
geisel = skio.imread('images/geisel.jpeg')
show_image(geisel)
print('Our beautiful campus.')

Images are made up of pixels. One of the most common ways to represent the color of a pixel is using the RGB format. In RGB, each color is described by three numbers – a red (R) value, a green (G) value, and a blue (B) value – each describing the "amount" of that base color that is present. The larger R is, the more red there is.

R, G, and B are each numbers between 0 and 255 inclusive, and we often express them together in a list or array (in the order R, then G, then B). So for example, `[255, 0, 0]` refers to the color red, and `[92, 45, 99]` refers to a dark-ish purple. [This tool](https://convertingcolors.com/rgb-color-92_45_99.html?search=RGB(92,%2045,%2099)) helps visualize what different RGB values look like.

<img src='images/rgbmodel.png' width = 250>

One way to apply filters to images is to apply mathematical functions to R, G, and B to calculate a new color for each pixel. That's exactly what you'll do in this question.

***Note:*** The code in this problem looks deceptively long and complicated – you only have to fill in ~7 lines total.

### Question 2a – Greyscale filter

The greyscale filter works like this:

$$
\begin{align*}
\text{new R} &= \frac{\text{old R} + \text{old G} + \text{old B}}{3} \\
\text{new G} &= \text{new B} = \text{new R}
\end{align*}
$$

That is, to convert a pixel to greyscale, you average its R, G, and B values.

Below, complete the implementation of `greyscale_filter`, which takes in an `np.array` `pixel` and returns a new `np.array` whose values are converted to greyscale. Example behavior is shown below.

```py
>>> greyscale_filter(np.array([50, 100, 150]))
array([100., 100., 100.])

>>> greyscale_filter(np.array([132, 213, 100]))
array([148.33333333, 148.33333333, 148.33333333])
```

***Note:*** Do not write `(pixel[0] + pixel[1] + pixel[2]) / 3`! Instead, use `np.mean`, a function which takes in an array and returns the mean of all values in the array.

<!--
BEGIN QUESTION
name: q5a
points: 1
-->

In [ ]:
def greyscale_filter(pixel):
    # Don't add any more lines!
    average = ...
    return np.array([average, average, average])

In [ ]:
grader.check("q5a")

Now that you've implemented your first filter function, it's time to see it in action. Run the cell below to convert our Geisel image to greyscale and display it. It may take ~10 seconds.

In [ ]:
# Don't worry about what this code is doing, just run it.
def apply_filter_to_image(image, filter_fn):
    new_image = np.zeros(image.shape)
    for x in range(image.shape[0]):
        for y in range(image.shape[1]):
            new_image[x][y] = filter_fn(image[x][y])
    
    return new_image.astype(int)

geisel_greyscale = apply_filter_to_image(geisel, greyscale_filter)

show_image(geisel_greyscale)

Cool!

### Question 2b – X-Ray filter

Another fun filter is the X-ray filter, which follows this rule:

$$
\begin{align*}
\text{new R} &= 255 - \frac{\text{old R} + \text{old G} + \text{old B}}{3} \\
\text{new G} &= \text{new B} = \text{new R}
\end{align*}
$$


Below, complete the implementation of `xray_filter`, which takes in an `np.array` `pixel` and returns a new `np.array` whose values are converted to x-ray. Example behavior is shown below.

```py
>>> xray_filter(np.array([50, 100, 150]))
array([155., 155., 155.])

>>> xray_filter(np.array([132, 213, 100]))
array([106.66666667, 106.66666667, 106.66666667])
```

***Note:*** `xray_filter` can be written in terms of `greyscale_filter`! In your work, you should not call `np.mean` or index into `pixel` at all. Instead, call `xray_filter` and see how you can use the properties of arrays to compute the rule above.

***Hint:*** `5 - np.array([1, 2, 3])` evaluates to `np.array([4, 3, 2])`.

<!--
BEGIN QUESTION
name: q2b
points: 1
-->

In [ ]:
def xray_filter(pixel):
    ...

In [ ]:
grader.check("q2b")

Let's see what the X-ray filter looks like:

In [ ]:
# Run this cell.
geisel_xray = apply_filter_to_image(geisel, xray_filter)
show_image(geisel_xray)

Spooky!

### Question 2c – Sepia filter

The last filter we will apply is the [sepia](https://raw.pics.io/sepia-image) filter, which will give our images a "historic" feel. The sepia filter follows this more complicated rule:

$$
\begin{align*}
\text{new R} &= (0.393 \cdot \text{old R}) + (0.769 \cdot \text{old G}) + (0.189 \cdot \text{old B}) \\
\text{new G} &= (0.349 \cdot \text{old R}) + (0.686 \cdot \text{old G}) + (0.168 \cdot \text{old B}) \\
\text{new B} &= (0.272 \cdot \text{old R}) + (0.534 \cdot \text{old G}) + (0.131 \cdot \text{old B})
\end{align*}
$$

If any of $\text{new R}$, $\text{new G}$, or $\text{new B}$ are greater than 255, we set them equal to 255.

In this question you will implement `sepia_filter` – but we want to let you know of a few `numpy` functions that you need to use (that will make your life easy)!

The first of these is `np.dot`. `np.dot` takes in two arrays, multiplies their elements pairwise, and sums together the result. If `x` and `y` are two arrays, `np.dot(x, y)` calculates `x[0]*y[0] + x[1]*y[1] + x[2]*y[2] + ...`. Here's an example:

In [ ]:
a = np.array([5, 1, 2])
b = np.array([1, -1, 4])

# Equal to 5*1 + 1*(-1) + 2 * 4
np.dot(a, b)

You should use `np.dot` to calculate $\text{new R}$, $\text{new G}$, and $\text{new B}$; it is **way** easier than manually writing out the formulas.

The other function we want you to know about is `np.clip`. `np.clip` takes in three arguments: an array, a lower bound, and an upper bound. It returns a new array where every element less than the lower bound is replaced with the lower bound, and every element greater than the upper bound is replaced with the upper bound. Here's an example:

In [ ]:
numbers = np.array([15, -1, 25, 18, 26, 4, 5, -4])

np.clip(numbers, 0, 20)

You will need to use `np.clip` before returning your results, because the dot products you perform may bring some RGB values below 0 or above 255, which is invalid.

In the cell below, complete the implementation of `sepia_filter`. Example behavior is shown below.

```py
>>> sepia_filter(np.array([50, 100, 150]))
array([124.9 , 111.25,  86.65])

>>> sepia_filter(np.array([132, 213, 100]))
array([234.573, 208.986, 162.746])
```

<!--
BEGIN QUESTION
name: q5c
points: 2
-->

In [ ]:
def sepia_filter(pixel):
    # Don't change any of red_coef, green_coef, or blue_coef
    red_coef = np.array([0.393, 0.769, 0.189])
    green_coef = np.array([0.349, 0.686, 0.168])
    blue_coef = np.array([0.272, 0.534, 0.131])
    
    # Remember to use np.dot (3 times) and np.clip at the end!
    ...

In [ ]:
grader.check("q5c")

Time to enjoy the fruits of our labor once again:

In [ ]:
# Run this cell
geisel_sepia = apply_filter_to_image(geisel, sepia_filter)
show_image(geisel_sepia)

### Fun Demo

Now that you've done all of the work necessary to implement three cool filters, it's only right that you get the chance to try them out on your own images.

**First**, run this cell. It will show you an "Upload" button which you can click to upload an image from your computer. **You must upload a `.jpg` image!** It will also show you a dropdown menu which will allow you to select from one of the three filters we created in this question. (Smaller images work faster.)

In [ ]:
def extract_array_from_upload(uploader):
    content = list(uploader.value.values())[0]['content']
    img = Image.open(io.BytesIO(content))
    arr = np.asarray(img)
    return arr

uploader = widgets.FileUpload(
    accept='.jpg',
    multiple=False
)

filter_select = widgets.Dropdown(
    options=['greyscale', 'x-ray', 'sepia'],
    value='sepia'
)

display(uploader)
display(filter_select)

Then, run the following cell to perform all of the necessary computation and output your filtered image.

In [ ]:
original_image = extract_array_from_upload(uploader)
print('Original image:')
show_image(original_image)
plt.show()

filter_map = {'greyscale': greyscale_filter, 'x-ray': xray_filter, 'sepia': sepia_filter}
image_converted = (apply_filter_to_image(original_image, filter_map[filter_select.value]))
print('Filtered image')
show_image(image_converted)

Who needs Instagram? 😎

## Question 3 – The Birthday "Paradox"

The Birthday "Paradox" involves the following question:

> How many students do you need in a class so that there is a 50% chance that at least two students have the same birthday?

What do you think the answer is? 10? 30? 150?

It turns out that we can find the answer by simulating, using functions built into `np.random`. Let’s assume that all birth dates are equally likely (and there are no leap years). Here's how we'd go about carrying out the simulation:

1. Generate random integers between 1 and 365, one at a time. 
2. Do this until two numbers are the same – this is the smallest class size in one “simulation” such that two students have the same birthday.
    - Pretend we’re drawing birthdays out of a hat, writing them down, and putting them back in. We stop once we draw the same birthday twice.
3. Repeat step 1 many times.


### Question 3a

Complete the implementation of the function `one_sum()` so that it follows steps 1 and 2 above. That is, it should randomly select integers between 1 and 365 repeatedly until it sees two of the same integer. When it sees two of the same integer, it should return the number of integers it has drawn (including the duplicate).

So for instance, if the sequence of numbers we draw is

12, 322, 19, 215, 103, 98, 9, 322

`one_sim` should return 8.

***Hint:*** You'll need a loop of some sort. 🤔

<!--
BEGIN QUESTION
name: q3a
-->

In [ ]:
def one_sim():
    ...

Once you've implemented `one_sim`, run the cell below several times to get a feel for the range of values that are typical.

In [ ]:
one_sim()

### Question 3b

Now, assign `class_sizes` to an array containing the results of calling `one_sim()` 100,000 times.

***Hint:*** You'll need to write another loop, and that's fine. It might take a while to run.

<!--
BEGIN QUESTION
name: q3b
-->

In [ ]:
class_sizes = ...
class_sizes

In [ ]:
grader.check("q3b")

Now that we've run our simulation many times, let's take a look at the results. Run the cell below.

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
plt.hist(class_sizes, density=True, bins=np.arange(0, 101, 1), ec='black')
plt.xlabel('class size')
plt.ylabel('density');

The histogram above contains class sizes on the x-axis and **density** on the y-axis. The y-axis is defined so that the total area of the histogram adds up to 1. To calculate probabilities using this histogram, we can just calculate areas.

These results may be surprising! It turns out that you don't need very many people in a class in order for the chance that two people share a birthday to be quite high.

Let's try and find the class size that divides the histogram in two. That class size will have the property that **50% of the time, a class with that many students will have two people that share the same birthday**.

In [ ]:
np.median(class_sizes)

Much smaller than you expected, right?

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
plt.hist(class_sizes, density=True, bins=np.arange(0, 101, 1), ec='black')
plt.xlabel('class size')
plt.ylabel('density');
plt.axvline(x=np.median(class_sizes), color='red', linewidth=3);